#!/bin/sh

base="bash-completion bspwm compton curl fcron git lxappearance openssh polybar rsync sxhkd tmux void-repo-nonfree wmctrl xdotool xorg xprop xtools"
post="alsa-utils pulseaudio intel-video-accel"
apps="dmenu docker docker-compose dunst evince firefox gthumb gtkwave htop i3lock-color iverilog mc neovim python3 rofi Thunar thunar-volman xautolock xst"
fonts="font-Siji font-tamzen liberation-fonts-ttf noto-fonts-ttf noto-fonts-ttf-extra terminus-font"

echo "\nStarting system update...\n"
sudo xbps-install -Suy

echo "\nStarting installation of packages...\n"
sudo xbps-install -Sy $base $post $apps $fonts


# Fetch vim-plug

curl -fLo ~/hometest/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
