#!/bin/sh

base="bash-completion bspwm compton curl dunst git htop i3lock-color lxappearance mc neovim polybar python3 rofi rsync sxhkd font-tamzen tmux void-repo-nonfree wmctrl xautolock xdotool xorg xprop xst"

sudo xbps-install -S -y $base

# Fetch vim-plug

curl -fLo ~/hometest/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
