#!/bin/bash

# Install vim plugins automatically
vim +PlugInstall +qall

# Add user to docker group and start docker daemon
sudo usermod -aG docker $USER
sudo ln -s /etc/sv/docker /var/service/
sudo sv start docker

# Download and install winbox
sudo mkdir -p /usr/share/winbox
curl -O https://download.mikrotik.com/winbox/3.22/winbox.exe && sudo mv winbox.exe /usr/share/winbox
