#! /bin/sh

sxhkd &

bspc monitor -d 'I' 'II' 'III' 'IV'

bspc config border_width 2
bspc config window_gap 30

bspc config -d ^4 border_width 2
bspc config -d ^4 window_gap 8


bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop=IV follow=on
bspc rule -a Thunar state=floating
bspc rule -a Lxappearance state=floating
