alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -laF'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias xin='sudo xbps-install'
alias xre='sudo xbps-remove'
alias xqe='xbps-query'
alias dh='df -h'
